product: lando
hyperdrive: hyperdrive
channel: stable
domain: lndo.site
mode: cli

dockerSupportedVersions:
  compose:
    min: "2.0.0"
    max: "2.99.99"
    link:
      linux: https://docs.docker.com/compose/install/#install-compose-on-linux-systems
  desktop:
    min: "4.0.0"
    max: "4.99.99"
    link:
      darwin: https://docs.docker.com/docker-for-mac/release-notes/
      win32: https://docs.docker.com/docker-for-windows/release-notes/
  engine:
    min: "26.99.9"
    max: "20.10.99"
    link:
      linux: https://docs.docker.com/engine/install/

landoFile: .lando.yml
