name: Check Plugins Installed

on:
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-20.04
    env:
      TERM: xterm
    strategy:
      matrix:
        plugins:
          - acquia
          - apache
          - backdrop
          - compose
          - dotnet
          - drupal
          - elasticsearch
          - go
          - joomla
          - lagoon
          - lamp
          - laravel
          - lemp
          - mailhog
          - mariadb
          - mean
          - memcached
          - mongo
          - mssql
          - mysql
          - nginx
          - node
          - pantheon
          - php
          - phpmyadmin
          - platformsh
          - postgres
          - python
          - redis
          - ruby
          - solr
          - symfony
          - tomcat
          - wordpress
          - varnish

    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # This block should eventually become use lando/actions-hyperdrive@v2
      - name: Verify Docker dependencies
        run: |
          docker --version | grep "20.10."
          docker-compose --version | grep "1.29."
      # - name: Install via hyperdrive if above is bad
      - name: Disable usage and error reporting
        run: |
          mkdir -p ~/.lando/cache
          echo false > ~/.lando/cache/report_errors
          sed -i "s/report: true.*/report: false/" config.yml
      - name: Package CLI
        run: |
          yarn add @lando/acquia@^0.5.0 @lando/apache@^0.5.0 @lando/backdrop@^0.5.0 @lando/dotnet@^0.5.0 @lando/drupal@^0.5.0 @lando/elasticsearch@^0.5.0 @lando/go@^0.5.0 @lando/joomla@^0.5.0 @lando/lagoon@^0.5.0 @lando/lamp@^0.5.0 @lando/laravel@^0.5.0 @lando/lemp@^0.5.0 @lando/mariadb@^0.5.0 @lando/mean@^0.5.0 @lando/mongo@^0.5.0 @lando/mssql@^0.5.0 @lando/mysql@^0.5.0 @lando/nginx@^0.5.0 @lando/node@^0.5.0 @lando/pantheon@^0.5.0 @lando/php@^0.5.0 @lando/platformsh@^0.6.0 @lando/postgres@^0.5.0 @lando/python@^0.5.0 @lando/redis@^0.5.0 @lando/ruby@^0.5.0 @lando/solr@^0.5.0 @lando/symfony@^0.5.0 @lando/tomcat@^0.5.0 @lando/varnish@^0.5.0 @lando/wordpress@^0.5.0
          yarn build:cli
      - name: Replace source CLI with packaged one
        run: sudo mv ./dist/@lando/cli /usr/local/bin/lando
      - name: Verify we can run the packaged CLI
        run: |
          lando version
          lando config

      # Checks to make sure the plugins listed in the matrix have the right path
      - name: Check if @lando/${{ matrix.plugins }} is installed correctly
        run: |
          lando config --path plugins | grep node_modules/@lando/${{ matrix.plugins }}
