name: Ship Dev CLI

on:
  push:
    branches:
      - main
      - 'preview/**'

jobs:
  package:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Package up the cli
      - name: Package CLI
        run: |
          yarn pkg --target=node${{ matrix.node-version }}-macos-x64
          yarn pkg --target=node${{ matrix.node-version }}-macos-arm64
          yarn pkg --target=node${{ matrix.node-version }}-linux-x64
          yarn pkg --target=node${{ matrix.node-version }}-linux-arm64
          yarn pkg --target=node${{ matrix.node-version }}-win-x64
      # Upload so we can reuse
      - name: Upload CLI
        uses: actions/upload-artifact@v2
        with:
          name: lando-build-${{ github.sha }}
          path: dist/
          if-no-files-found: error
          retention-days: 1

  process:
    runs-on: ${{ matrix.os }}
    needs:
      - package
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macos-10.15
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/download-artifact@v2
          with:
            name: lando-build-${{ github.sha }}
            path: dist
        - name: Display structure of downloaded files
          run: ls -R
          working-directory: dist
